petshop/petshop/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^export-exl/$', views.export, name='export'),
    url(r'^export-csv/$', views.export, name='export'),
    path('', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('task/', include('tasks.urls')),
    #-------------------debug_toolbar----------------------#
    path('__debug__/', include(debug_toolbar.urls)),
    #-------------------debug_toolbar-end---------------------#

    
]

petshop/tasks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from tasks.views import DetailAndDelete, ListAndCreate




urlpatterns = [
    path('', views.Pagina),
    path('search', views.Pesquisa, name="search"),
    path('cadastro', views.Cadastro, name="cadastro"),
    path('sucesso', views.Sucesso, name="Sucesso"),
    path('login', views.Login, name="login"),
    path('usuario', views.Usuario, name="usuario"),
    path('sobre_nos', views.Sobre, name="sobre_nos"),
    path('loja', views.Ecommerce_Categorias, name="loja"),
    path('loja-produtos/<int:product_id>',views.Ecommerce_Categoias_lista, name="loja-produtos"),
    path('produtos_detalhes/<int:id>/',views.Detalhes_Produtos, name="produtos_detalhes"),
    path('dados', ListAndCreate.as_view()),
    path('dados/<int:pk>', DetailAndDelete.as_view()),
    path('add-to-cart', views.add_to_cart, name="add_to_cart"),
    path('cart', views.Cart_list, name="cart"),
    path('delete-from-cart', views.delete_cart_item, name="delete-from-cart"),

]

#--------------adicionando imagem no ecommerce-------#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petshop/ecommerce/models.py
from django.db import models
from django.utils.html import mark_safe




#Categoria
class Category(models.Model):
    title = models.CharField(max_length=100,
    verbose_name='categoria do produto')

    image = models.ImageField(upload_to="dadosCategory/",
    verbose_name='imagem do produto')

    class Meta:  # verbose_name_plural substitui o nome no banco de dados na pagina do admin
        verbose_name_plural = '1.Categorias'

    def __str__(self):
        return self.title


#Marca
class Brand(models.Model):
    title = models.CharField(max_length=100,
    verbose_name='marca do produto')

    image = models.ImageField(upload_to='dadosBrand/',
    verbose_name='imagem do produto')

    class Meta:  # verbose_name_plural substitui o nome no banco de dados na pagina do admin
        verbose_name_plural = '3.Marcas'

    def __str__(self):
        return self.title


#Tamanho 
class Size(models.Model):
    title = models.CharField(max_length=100,
    verbose_name='tamanho do produto')

    class Meta:  # verbose_name_plural substitui o nome no banco de dados na pagina do admin
        verbose_name_plural = '4.Peso'

    def __str__(self):
        return self.title


#Modelo do Produto
class Product(models.Model):
    title = models.CharField(max_length=200, verbose_name='titulo do produto')
    #forem adicionadas ficaram guardadas na pasta 
    # upload_to ciria uma pasta e todas as fotos que
    image = models.ImageField(upload_to='dadosProduct/')
    slug = models.CharField(max_length=400)
    detail = models.TextField(verbose_name='detalhes')
    specs = models.TextField(verbose_name='especificações')
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    #models.BooleanField(default=True) apresenta a opção para flegar se esta valida ou não
    status = models.BooleanField(default=True)
    #is_featured vai ser habilitado para mostrar os produtos em destaque na pagina inicial
    is_featured = models.BooleanField(
        default=False, verbose_name='visivel na pagina principal')
    class Meta:  # verbose_name_plural substitui o nome no banco de dados na pagina do admin
        verbose_name_plural = '2.Produtos'

    def __str__(self):
        return self.title





# Atributos do Produto
class ProductAttribute(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Produto')
    size = models.ForeignKey(
        Size, on_delete=models.CASCADE, verbose_name='Tamanho')
    price = models.CharField(max_length=100, verbose_name='Preço')
    # upload_to ciria uma pasta e todas as fotos que
    image = models.ImageField(upload_to='dadosProduct/')

    class Meta:  # verbose_name_plural substitui o nome no banco de dados na pagina do admin
        verbose_name_plural = '5.Atributos do Produto'

    def __str__(self):
        return self.product.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" height="80"/>' % (self.image.url))

petshop/tasks/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth import get_user_model

STATUS = (
    ('pendente', 'Pendente'),
    ('finalizado', 'Finalizado'),
)

TYPE = (
    ('gato' , 'Gato'),
    ('cachorro' , 'Cachorro'),
    ('passaro' , 'Passaro'),
    ('hamster', 'Hamster'),
    ('peixe', 'Peixe'),
    ('coelho', 'Coelho'),
    ('porquinho_da_índia', 'Porquinho da índia'),
)

TIME = (
    ('9:00', '9:00'),
    ('10:00', '10:00'),
    ('11:00', '11:00'),
    ('12:00', '12:00'),
    ('13:00', '13:00'),
    ('14:00', '14:00'),
    ('15:00', '15:00'),
    ('16:00', '16:00'),
    ('17:00', '17:00'),
    ('18:00', '18:00'),
    ('19:00', '19:00'),
    ('20:00', '20:00'),
)

class Task(models.Model):
    cpf = models.CharField(
        max_length=11,
        verbose_name='digite seu cpf',

    )
    phone = models.CharField(
        max_length=11, 
        verbose_name='Telefone', 

    )
    email = models.EmailField(
        blank=True, 
        null=True,
        verbose_name='E-mail', 

    )
    name = models.CharField(
        max_length=100,
        verbose_name="Nome do animal"
    )
    animal_race = models.CharField(
    max_length=100,
    choices=TYPE,
    verbose_name='Tipo de animal',
    )

    problem = models.TextField(
        max_length=100, 
        verbose_name="sintoma do animal"
    )

    appointment_date = models.DateField(
        verbose_name="data de agendamento (mm/dd/2021)",
    )

    hours = models.CharField(
        max_length=5,
        verbose_name="horario do agendamento",
        choices=TIME,
    )

    done = models.CharField(
        verbose_name="Status",
        max_length=15,
        choices=STATUS,
    )
    
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Usuario",)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "Task"

    class Meta:  # substitui o nome no banco de dados na pagina do admin
        verbose_name_plural='Cadastros dos Usuarios'

    def __str__(self):
        return self.name

petshop/tasks/forms.py
from django import forms

from .models import Task


class AddData(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('cpf', 'phone', 'email', 'name',
                  'animal_race', 'problem', 'appointment_date', 'hours')

petshop/tasks/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404
from rest_framework import generics
from ecommerce.models import Category, Product
from tasks.serializer import TodoSerializers
from django.template.loader import render_to_string
from .models import Task
from .forms import AddData
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from django.http import HttpResponse
from tasks.resources import TaskResources

#================paginas que usuario acessa sem estar logado logado begin=======================

#Pagina de apresentação 
def Pagina(request):
    data = Product.objects.filter(is_featured=True).order_by('-id')
    return render(request, 'tasks/pagina_principal.html', {'data': data})

#pagina sobre nos
def Sobre(request):
    return render(request, 'about/sobre_nos.html')


#barra de pesquisa
def Pesquisa(request):
    q = request.GET['q']
    data = Product.objects.filter(title__icontains=q).order_by('-id')
    return render(request, 'tasks/search.html', {'data': data})

#===============Ecommerce begin======================

#categoria dos produtos
def Ecommerce_Categorias(request):
    data = Category.objects.all().order_by('-id')
    return render(request, 'e-commerce/ecommerce_categorias.html', {'data': data})

#lista de produtos
def Ecommerce_Categoias_lista(request, product_id):
    category = Category.objects.get(id=product_id)
    # interage o banco Category com o banco Product, objects.filter pega todos os dados do banco
    data = Product.objects.filter(category=category).order_by('-id')
    return render(request, 'e-commerce/ecommerce_categorias_lista.html', {'data': data})

#detalhes dos produtos
def Detalhes_Produtos(request,id):
    product = Product.objects.get(id=id)
    return render(request, 'e-commerce/product_detail.html', {'data': product})


# estrutura para comando de adicionar pedidos a sacola
def add_to_cart(request):
	# del request.session['cartdata']
	cart_p = {}
    #quando requerir o id solicitados que ele pegue dados especificos do id em que selecionou 
    #como image,title,qty e price 
	cart_p[str(request.GET['id'])] = {
		'image': request.GET['image'],
        'title': request.GET['title'],
		'qty': request.GET['qty'],
		'price': request.GET['price'],
	}
	if 'cartdata' in request.session:
        #se o requerimento for um id valido vai chamar a variavel cartdata
		if str(request.GET['id']) in request.session['cartdata']:
			cart_data = request.session['cartdata']
			cart_data[str(request.GET['id'])]['qty'] = int(
			    cart_p[str(request.GET['id'])]['qty'])
			cart_data.update(cart_data)
			request.session['cartdata'] = cart_data
		else:
			cart_data = request.session['cartdata']
			cart_data.update(cart_p)
			request.session['cartdata'] = cart_data
	else:
		request.session['cartdata'] = cart_p
	return JsonResponse({'data': request.session['cartdata'], 'totalitems': len(request.session['cartdata'])})



# Pagina da sacola de pedidos
#total_amt faz a soma de todos os produtos selecionados no carrinho 
def Cart_list(request):
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty'])*float(item['price'])
    return render(request, 'e-commerce/cart.html', {'cart_data': request.session['cartdata'], 'totalitems': len(request.session['cartdata']), 'total_amt': total_amt})


#deletar item da Pagina da sacola de pedidos
def delete_cart_item(request):
	p_id = str(request.GET['id'])
	if 'cartdata' in request.session:
		if p_id in request.session['cartdata']:
			cart_data = request.session['cartdata']
			del request.session['cartdata'][p_id]
			request.session['cartdata'] = cart_data
	total_amt = 0
	for p_id, item in request.session['cartdata'].items():
		total_amt += int(item['qty'])*float(item['price'])
	t = render_to_string('ajax/cart_list.html', {'cart_data': request.session['cartdata'], 'totalitems': len(
	    request.session['cartdata']), 'total_amt': total_amt})
	return JsonResponse({'data': t, 'totalitems': len(request.session['cartdata'])})

#====================Ecommerce End=================================
#==================Paginas sem usuario estar logado End===================


#==================Paginas com usuario logado Begin======================
@login_required
def Sucesso(request):
    return render(request, 'tasks/sucesso.html')



@login_required
def Cadastro(request):
    if request.method == 'POST':
        form = AddData(request.POST)

        if form.is_valid():
            task = form.save(commit=False)
            task.done = 'pendente'
            task.user = request.user
            task.save()
            
        return render(request, 'tasks/sucesso.html')
    else:
        form = AddData()
        return render(request, 'tasks/cadastro.html', {'form' : form })

        
@login_required
def Login(request):
    return render(request, 'tasks/login.html')


@login_required
def Usuario(request):
    table = Task.objects.all()
    tasks_list = Task.objects.all().order_by('-created_at').filter(user=request.user)
    paginator = Paginator(tasks_list, 4)

    page = request.GET.get('page')
    tasks = paginator.get_page(page)
    return render(request, 'tasks/tela_usuario.html', {'tasks': tasks, 'table': table})

#==============Paginas com usuario logado End=================== 
    



#========Funções da api REST Begin=============
class ListAndCreate(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TodoSerializers

class DetailAndDelete(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TodoSerializers

#========Funções da api REST End=============



#===========Função da pagina do admin Begin==========
#importação e exportação de arquivos 
def export(request):
    tasks_resource = TaskResources()
    dataset = tasks_resource.export()
    response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="persons.xls"'
    return response
#===========Função da pagina do admin END==========

petshop/tasks/templates/tasks/cadastro.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Cadastro de usuário{% endblock  %}

{% block content %}
<!--cadastro de novo usuario Begin-->
<section id="content" style="background-image: url('{% static 'images/papel_de_parede_agendamento.jpg'%}');">
   <div class="content-wrap">
      <div class="container clearfix" >
         <div class="tabs mx-auto mb-0 clearfix ui-tabs ui-corner-all ui-widget ui-widget-content" id="tab-login-register" style="max-width: 500px;">
            <div class="tab-container">
               <div class="tab-content ui-tabs-panel ui-corner-bottom ui-widget-content" id="tab-register" aria-labelledby="ui-id-2" role="tabpanel" aria-hidden="false" style="display: block;">
                  <div class="card mb-0">
                     <div class="card-body" style="padding: 40px;">
                        <h3>Agende sua Consulta</h3>

                        <form id="register-form" name="register-form" class="row mb-0" action="#" method="post">
                           <div class="col-12 form-group">
                              <!-- faz CRUD do banco Task para o template-->
                              {% csrf_token %}
                              {{ form|crispy }}
                           </div>
                           <div class="col-12 form-group">
                              <button class="button button-3d button-black m-0" id="register-form-submit" name="register-form-submit" value="register">Register Now</button>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
<!--cadastro de novo usuario End-->
{% endblock %}

petshop/tasks/templates/tasks/pagina_principal.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Pagina principal{% endblock  %}

{% block content %}

<!--tela de apresentação quando acessa o link da pagina Begin-->
<header>
   <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
         <div class="carousel-item active" style="background-image: url('{% static 'images/tela_principal.jpg'%}');">
            <div class="carousel-caption">
               <h1 style="color: black; font-size: 3.75rem;">Pet Mania</h1>
               <p class="text-black-60 mb-0">Serviço veterinario e cuidado higienico para seu pet</p>
            </div>
         </div>
      </div>
   </div>
</header>
<!-- apresentação Begin-->
<section class="py-5">
   <div class="container">
      <h1 class="fw-light">Venha conhecer nosso serviço</h1>
      <p class="lead">Só quem é apaixonado por animais sabe: a relação de amor e cumplicidade que temos com nossos bichinhos de estimação
         é um vínculo único! Por essa razão, não medimos esforços para oferecer o que há de melhor para trazer ainda mais alegria e qualidade de vida.
      </p>
   </div>
</section>
<!--apresentação End-->
<section class="py-5">
   <div class="container">
   <h1 class="fw-light">Conheça nossos Produtos</h1>
   <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
         <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
               {% for product in data %}
               <div class="col mb-5">
                  <div class="card h-100">
                     <!-- Product image-->
                     <img class="card-img-top" src="/media/{{product.productattribute_set.first.image}}" alt="{{product.title}}" />
                     <!-- Product details-->
                     <div class="card-body p-4">
                        <div class="text-center">
                           <h5 class="fw-bolder">{{product.title}}</h5>
                           <span >R$ {{product.productattribute_set.first.price}}</span>
                        </div>
                     </div>
                     <!-- Product actions-->
                     <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="/produtos_detalhes/{{product.id}}">Clique aqui</a></div>

                     </div>
                  </div>
               </div>
               {% endfor %}
            </div>
         </div>
         <div class="text-center">
            <a href="{% url 'loja' %}" class="button button-small button-dark button-rounded"><i class="icon-window-restore"></i>Mostrar todos os produtos</a>
         </div>
      </div>
   </div>
</section>
<!--tela de apresentação quando acessa o link da pagina end-->
{% endblock %}

petshop/tasks/templates/tasks/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Loja-Categorias{% endblock  %}


{% block content %}
<html lang="en">

    <body>
        <!-- Aba de pesquisa da pagina Begin-->
        <section class="py-3">
			<h1 style="text-align: center;"><span class="text-muted">resultado: </span>{{request.GET.q}} </h1>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
					{% if data %}
						{% for product in data %}
						<div class="col mb-5">
							<div class="card h-100">
								<!-- Product image-->
								<img class="card-img-top" src="/media/{{product.image}}" alt="{{product.title}}" />
								<!-- Product details-->
								<div class="card-body p-4">
									<div class="text-center">
										<h5 class="fw-bolder">{{product.title}}</h5>
									</div>
								</div>
								<!-- Product actions-->
								<div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
									<div class="text-center"><a class="btn btn-outline-dark mt-auto" href="/loja-produtos/{{product.id}}">Clique aqui</a></div>
								</div>
							</div>
						</div>
						{% endfor %}
					{% endif %}
                </div>
            </div>
        </section>
		<!-- Aba de pesquisa da pagina End-->
    </body>
{% include 'footer.html' %}
</html>
{% endblock %}

petshop/tasks/templates/tasks/sucesso.html
{% extends 'base.html' %}
{% load static %}

{% block title %}cadastro feito com sucesso{% endblock  %}

{% block content %}

<!--pagina apresentando que o cadastro foi realizado com sucesso  -->
<div class="py-5 bg-image-full" style="background-image: url('{% static 'images/cadastro_bem_sucedido.jpg'%}');">
    <div style="height: 20rem"></div>
    <div class="container clearfix">
        <h1 style="margin-top: -271px;color: aliceblue;">Cadastro efetuado com sucesso</h1>
	</div>
</div>
<section>
    <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold">Agora é somente aguardar</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Seu agendamento foi cadasrtado com sucesso e ja foi encamihado para nosso sistema,
            é orientado ao chegar no consultorio, apresente RG do usuario cadastrado.</p>
             <a href="{% url 'usuario' %}" class="button button-border button-circle button-dark">Retorne para a pagina principal</a>
        </div>
    </div>
</section>
<!--end-->

{% endblock %}

petshop/tasks/templates/tasks/tela_usuario.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Usuario-{{ request.user.username.title }}{% endblock  %}

{% block content %}
<body>
   <!--logo de bem vindo -->
   <header class="py-5 bg-image-full" style="background-image: url('{% static 'images/primeira_tela_fundo.jpg'%}');">
      <div class="text-center my-5">
         <h1 class="text-white fs-3 fw-bolder">Bem-Vindo, {{ request.user.username.title }} </h1>
      </div>
   </header>
   <!-- end -->
   <!--tabela e paginação de agendamentos ja cadastrados, visiveis ao usuario -->
   <section class="pagination">
      <div class="container my-5">
         <table class="table">
                  <h1 style="text-align: center;">Agendamentos cadastrados</h1>
            <thead>
               <tr>
               <th>Status</th>
               <th>Nome do Pet</th>
               <th>Data Agendada</th>
               <th>Horario</th>
               </tr>
            </thead>
            {% for task in tasks %}
            {% if task.done == 'pendente' %}
            <li class="task-item">
               {% else %}
            <li class="task-item done">
               {% endif %}
               <tbody>
                  <tr>
                  <td>{{task.done}}</td>
                  <td>{{task.name}}</td>
                  <td>{{task.appointment_date}}</td>
                  <td>{{task.hours}}</td>
                    
                  </tr>
               </tbody>
            </li>
            {% endfor %}
         </table>
         <ul class="pagination">
            {% if tasks.has_previous %}
            <li class="page-item">
               <a class="page-link" href="?page={{ tasks.previous_page_number }}" aria-label="Previous"> 
               <span aria-hidden="true">
               Anterior
               </span>
               </a>
            </li>
            {% endif %}
            <li class="page-item">
               {{ tasks.number }} de {{ tasks.paginator.num_pages }}
            </li>
            {% if tasks.has_next %}
            <li class="page-item">
               <a class="page-link" href="?page={{ tasks.next_page_number }}" aria-label="Next">
               <span aria-hidden="true">
               Proximo
               </span>
               </a>
            </li>
            {% endif %}          
         </ul>
      </div>
   </section>
   <!--end-->
   <!-- segunda imagem de fundo-->
   <div class="py-5 bg-image-full" style="background-image: url('{% static 'images/segunda_tela_fundo.jpg'%}');">
      <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
      <div style="height: 20rem"></div>
   </div>
   <!--end-->
   <!-- Serviço de agendamento de consulta-->
   <section class="py-5">
      <div class="container my-5">
         <div class="row justify-content-center">
            <div class="col-lg-6">
               <h2>Conheça nosso serviço veterinario.</h2>
               <p class="lead">Nosso serviço conta com os melhores profissionais na area.</p>
               <a href="{% url 'cadastro' %}" class="button button-border button-circle button-dark">Agende uma consulta</a>
            </div>
         </div>
      </div>
   </section>
   <!--end-->
   <!-- Serviço de agendamento de consulta-->
   <section class="py-5">
      <div class="container my-5">
         <div class="row justify-content-center">
            <div class="col-lg-6">
               <h2>Venha conhecer nossos Produtos</h2>
               <p class="lead">Conheça nossos diversos produtos para seus bichinhos.</p>
               <a href="{% url 'loja' %}" class="button button-border button-circle button-dark">Visite nossa loja</a>
            </div>
         </div>
      </div>
   </section>
   <!--end-->
{% include 'footer.html' %}
</body>
{% endblock %}